name: charity_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1
  intl: ^0.17.0
  toast: ^0.1.5
  shared_preferences: ^2.0.5
  modal_bottom_sheet: ^2.0.0
  url_launcher: ^5.7.10
  convex_bottom_bar: ^3.0.0
  carousel_slider: ^3.0.0


  # Provider + Stack pattern
  provider: ^5.0.0
  get_it: ^6.0.0
  auto_route: ^0.6.9
  injectable: ^1.0.7
  stacked: ^2.1.1
  stacked_services: ^0.6.7

  # Network
  connectivity: ^2.0.2

  #UI plugin
  auto_size_text: ^2.1.0
  theme_provider: ^0.5.0

  #Animation Plugin
  #  rive: ^0.6.8
  lottie: ^0.7.0+1

  # Icon Plugin
  fleva_icons: ^1.0.2
  flutter_vector_icons: ^0.3.0
  ionicons: ^0.1.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700

  assets:
      - assets/
      - assets/lottie/
      - assets/strings/
      - assets/svg/
      - assets/image/
      - assets/svg/services/
      - assets/svg/auth/

  uses-material-design: true


